import type {
  DailyLessonSeed,
  FoundationGroupSeed,
  LearningResource,
  LearningRoadmapSeed,
  PrerequisitesGroup,
  RoadmapModule,
  RoadmapStage,
  RouteFamilySeed,
} from "../data/learning-catalog-v3.js";

const CAVEAT_CN =
  "学习路线是面向 IC 研究与工程训练的结构化导览，可用于规划学习、读论文和小项目；正式设计、流片或发表前，请回到教材、数据手册、论文原文和指导教师或专业意见复核公式、指标与设计判断。";

const LESSON_TEMPLATE_CN: Record<string, string> = {
  problem: "说明这个电路或系统真正要解决的问题，以及它通常出现在什么类型的 IC 论文里。",
  intuition: "用工程直觉解释核心机制，先建立可迁移的判断框架。",
  minimalBlock: "补一个最小电路、系统框图或伪代码草图，帮助把概念落到结构上。",
  equations: "列出必要公式，并说明每个公式成立的前提和容易误用的地方。",
  specs: "定义关键指标、单位、测试条件和常见 benchmark 口径。",
  tradeoffs: "解释主要设计取舍，以及为什么不同论文会选择不同工作点。",
  pitfalls: "列出常见的硅后、测试、分类或 benchmark 陷阱。",
  paperDirections: "连接到代表性论文方向、会议和可继续追踪的关键词。",
  searches: "给出 SiliconScope 检索词和主题过滤入口。",
  quiz: "补几道快速自测题，检查是否真正理解概念。",
  next: "建议下一节内容和一个可以立刻动手的小项目。",
};

const targetUserLabels: Record<string, string> = {
  "IC students": "IC 学生",
  "research interns": "科研实习生",
  "graduate researchers": "研究生 / 科研新人",
  "industry engineers": "产业工程师",
};

const routeFamilies: Record<string, Pick<RouteFamilySeed, "title" | "description">> = {
  "ic-design": {
    title: "IC 设计路线",
    description: "覆盖模拟、数模混合、ADC/DAC、PLL/时钟、RF/mmWave、SerDes、PMIC、传感与存储 / CIM 等核心芯片设计方向。",
  },
  "digital-system": {
    title: "数字与系统路线",
    description: "覆盖 RTL、ASIC、后端、验证、体系结构、加速器和 FPGA 等数字系统方向。",
  },
  "device-manufacturing": {
    title: "器件与制造路线",
    description: "覆盖器件物理、工艺集成、功率器件、先进封装、半导体设备、材料和制造策略。",
  },
  "tools-quality-security": {
    title: "工具、质量与安全路线",
    description: "覆盖 EDA、模拟版图、硬件安全、验证文化、可靠性和汽车芯片产品化。",
  },
  frontier: {
    title: "前沿交叉路线",
    description: "偏研究型的交叉方向，适合在已有电路、体系结构或器件基础后进入。",
  },
};

const foundationGroups: Record<string, Pick<FoundationGroupSeed, "title" | "note" | "items">> = {
  "Math and Signals": {
    title: "数学与信号",
    note: "电路、系统、器件和 EDA 共用的底层语言。",
    items: ["微积分与微分方程", "线性代数", "概率统计", "复频域分析", "信号与系统", "优化基础"],
  },
  "Devices and Physics": {
    title: "器件与物理",
    note: "理解 PDK、寄生、工艺波动和可靠性所需的物理基础。",
    items: ["电磁学", "固体物理", "半导体器件", "噪声机制", "工艺波动", "可靠性基础"],
  },
  "Circuits and Systems": {
    title: "电路与系统",
    note: "进入细分方向前需要补齐的最小电路底座。",
    items: ["电路分析", "模拟电子学", "数字逻辑", "反馈与稳定性", "采样与量化", "计算机组成"],
  },
  "Engineering Tools": {
    title: "工程工具",
    note: "把知识变成可复现实验和项目的实践层。",
    items: ["Linux 与 Git", "Python 或 MATLAB", "SPICE 仿真", "Verilog/SystemVerilog", "Cadence/Synopsys/Siemens EDA", "论文阅读与 benchmark 表格"],
  },
};

const routeText: Record<
  string,
  Partial<Pick<LearningRoadmapSeed, "title" | "shortTitle" | "subtitle" | "description" | "outcomes" | "projectIdeas">>
> = {
  "analog-mixed-signal": {
    title: "模拟与数模混合 IC",
    shortTitle: "模拟 IC",
    subtitle: "运放、基准、滤波器、ADC/DAC 接口、PLL 支撑模块、版图、噪声、失配与测试。",
    description: "面向想读懂 ISSCC/JSSC 模拟论文并逐步进入晶体管级设计的核心路线。",
    outcomes: ["读懂模拟 IC 论文中的关键指标", "建立行为级与晶体管级仿真闭环", "把原理图、版图、寄生和测试结果连起来"],
    projectIdeas: ["做一本两级运放设计 notebook", "整理 bandgap 参考源论文指标表", "按模块和指标给模拟论文分类"],
  },
  "data-converters": {
    title: "数据转换器：ADC 与 DAC",
    shortTitle: "ADC / DAC",
    subtitle: "SAR、pipeline、delta-sigma、time-interleaved ADC，DAC 线性度、校准、FoM 与测试。",
    description: "帮助读者真正理解转换器论文，而不是只背 FoM 表格。",
    outcomes: ["正确阅读 ENOB/SNDR/FoM", "区分 SAR、pipeline、delta-sigma 和 TI ADC 的取舍", "建立公平的 benchmark 表格"],
    projectIdeas: ["做一张 ADC benchmark 表", "搭一个 SAR ADC 行为模型", "写一页 FoM 陷阱笔记"],
  },
  "mixed-signal-system-integration": {
    title: "数模混合 IC 系统集成",
    shortTitle: "数模混合",
    subtitle: "模拟/数字边界、校准环路、时钟/复位跨域、传感器/ADC/PLL/PMIC 集成、AMS 验证与硅后 bring-up。",
    description: "连接模拟模块、数字控制、寄存器、校准、时钟、电源域和验证的桥梁路线，补上纯模拟与纯 RTL/SoC 之间最容易缺失的工程层。",
    outcomes: ["设计数模混合控制与校准接口", "读懂把电路创新和数字辅助结合的论文", "为模拟占比较高的 SoC 规划验证和 bring-up"],
    projectIdeas: ["为 SAR ADC 设计混合信号寄存器表", "给 PLL 写一份 AMS 验证计划", "梳理 ADC/PLL/SerDes 论文中的校准分类"],
  },
  "clocking-pll-timing": {
    title: "时钟、PLL 与时序",
    shortTitle: "PLL / 时钟",
    subtitle: "电荷泵 PLL、ADPLL、fractional-N、MDLL、注入锁定、jitter、相位噪声、spur 与时钟分配。",
    description: "理解 RF、有线高速接口、数字 SoC 和数据转换器系统里常见时钟电路的路线。",
    outcomes: ["把相位噪声换算到 jitter", "理解 PLL 架构选择", "读懂 spur 和 lock-time 指标"],
    projectIdeas: ["做一个相位噪声到 jitter 的计算器", "按架构给 PLL 论文分类", "整理一张 spur 来源 checklist"],
  },
  "wireline-serdes": {
    title: "有线高速接口与 SerDes",
    shortTitle: "SerDes",
    subtitle: "高速链路、信道、均衡、CDR、PAM4、时钟、测试和 die-to-die 接口。",
    description: "连接模拟、时钟、数字信号处理、封装信道和系统带宽的桥梁路线。",
    outcomes: ["读懂眼图和 bathtub 曲线", "理解 CTLE/DFE/CDR 取舍", "把信道损耗和均衡器设计连起来"],
    projectIdeas: ["做一个简化信道/均衡 notebook", "建立 SerDes 论文分类表", "按数据率和 pJ/bit 对比 PAM4 链路论文"],
  },
  "rf-mmwave": {
    title: "射频与毫米波 IC",
    shortTitle: "RF/mmWave",
    subtitle: "LNA、mixer、VCO、PA、相控阵、beamforming、RF 测试、EM、封装与系统预算。",
    description: "从低频电路直觉进入 RF/mmWave 现实：匹配、S 参数、噪声系数、线性度、EM 版图、封装寄生、相控阵和测试设置都会成为设计的一部分。",
    outcomes: ["阅读 RF 收发链路论文", "理解 LNA/PA/mixer/VCO 的关键取舍", "把 EM/封装/测试和硅片结果连起来"],
    projectIdeas: ["做 RF 指标速查卡", "搭一个接收机级联预算计算器", "对比近期相控阵论文"],
  },
  "power-management": {
    title: "电源管理 IC（PMIC）",
    shortTitle: "PMIC",
    subtitle: "LDO、buck/boost、switched-capacitor、hybrid converter、电池管理、数字控制、瞬态响应、效率和系统供电。",
    description: "面向 DC-DC、LDO 和系统供电的路线。分类时应把 converter 论文归到 PMIC，而不是误归到 RF。",
    outcomes: ["区分 LDO、inductive、switched-capacitor 和 hybrid converter", "读懂效率、瞬态和 PSRR 指标", "把 PMIC 论文连接到 SoC/电池/封装约束"],
    projectIdeas: ["做一套 converter 分类规则", "审计 PMIC 机构画像口径", "整理效率/瞬态 benchmark 表"],
  },
  "sensor-bio-interface": {
    title: "传感与生物接口 IC",
    shortTitle: "Sensor / Bio",
    subtitle: "AFE、低噪声前端、图像传感器、bio-signal、神经接口、MEMS、读出链路和低功耗系统。",
    description: "把模拟前端、传感器物理、ADC、低功耗系统和应用场景连起来的路线。",
    outcomes: ["读懂 sensor/biomedical AFE 论文", "理解低噪声与低功耗前端取舍", "把传感器、读出和系统指标连起来"],
    projectIdeas: ["整理 AFE 噪声预算", "对比图像传感器 column ADC 论文", "做传感器接口论文分类表"],
  },
  "digital-asic": {
    title: "数字 ASIC 与 SoC",
    shortTitle: "数字 ASIC",
    subtitle: "RTL、FSM、总线、缓存、CDC、低功耗、SoC 集成、体系结构论文和硅后验证。",
    description: "从可综合 RTL 到 SoC 系统思维的路线，适合想进入数字芯片设计和系统集成的读者。",
    outcomes: ["写出可维护的 RTL 和状态机", "理解 SoC 集成、CDC 与低功耗约束", "读懂数字芯片和架构论文指标"],
    projectIdeas: ["实现一个小型 DMA 或 FIFO 子系统", "写 CDC 风险 checklist", "按数据流给 SoC 论文分类"],
  },
  "digital-backend-physical-design": {
    title: "数字后端与物理设计",
    shortTitle: "数字后端",
    subtitle: "STA、floorplan、placement、CTS、routing、IR drop、EM、signoff 和时序收敛。",
    description: "把 RTL 变成可制造版图的路线，重点理解时序、功耗、拥塞、物理约束和 signoff。",
    outcomes: ["读懂 setup/hold 时序报告", "理解 PnR 与 CTS 的核心取舍", "建立 signoff 思维"],
    projectIdeas: ["做一个时序报告 dashboard", "整理 CTS 问题 checklist", "比较开源 PnR flow 的拥塞结果"],
  },
  "verification-dft": {
    title: "验证、DFT 与硅后测试",
    shortTitle: "验证 / DFT",
    subtitle: "仿真、断言、覆盖率、formal、CDC、scan、ATPG、BIST、硅后测试和可测性设计。",
    description: "面向把设计风险提前暴露的路线，覆盖功能验证、形式验证、可测性和硅后测试。",
    outcomes: ["设计可执行的验证计划", "使用断言、覆盖率和 formal 发现问题", "理解 scan/ATPG/BIST 与硅后测试"],
    projectIdeas: ["给一个小 RTL 模块写 SVA", "做 CDC 风险样例库", "整理 DFT/scan 术语卡"],
  },
  "architecture-accelerator": {
    title: "体系结构与 AI 加速器",
    shortTitle: "架构 / 加速器",
    subtitle: "dataflow、memory hierarchy、systolic array、NPU、精度、稀疏性、TOPS/W 和系统 benchmark。",
    description: "从算法和数据流进入芯片架构的路线，强调指标口径、存储墙和真实 workload。",
    outcomes: ["理解加速器数据流和存储层次", "识别 TOPS/W benchmark 陷阱", "把架构论文和实现代价连起来"],
    projectIdeas: ["实现一个小 systolic array 模拟器", "整理 TOPS/W 口径差异", "给 AI 加速器论文做 memory bottleneck 表"],
  },
  "fpga-reconfigurable": {
    title: "FPGA 与可重构计算",
    shortTitle: "FPGA",
    subtitle: "LUT/BRAM/DSP、时序收敛、流式加速、HLS、固定点、原型验证和 FPGA 到 ASIC 的迁移。",
    description: "用 FPGA 建立硬件实现直觉，并理解原型、加速和 ASIC 化之间的差异。",
    outcomes: ["理解 FPGA 资源与时序指标", "实现流式硬件加速器", "判断 FPGA 原型和 ASIC 设计的差异"],
    projectIdeas: ["做一个 streaming accelerator", "比较固定点位宽影响", "把 FPGA 原型改写成 ASIC 友好的结构"],
  },
  "memory-cim": {
    title: "存储器与存内计算",
    shortTitle: "Memory / CIM",
    subtitle: "SRAM、DRAM、NVM、bitcell、sense amp、CIM、模拟计算、ADC overhead 和系统映射。",
    description: "连接存储电路、器件限制和计算架构的路线，尤其适合读 SRAM/CIM 论文。",
    outcomes: ["理解 SRAM 稳定性和读写裕量", "读懂 CIM 电路和系统指标", "识别 ADC/外围电路 overhead"],
    projectIdeas: ["画一张 SRAM read stability 笔记", "比较 analog CIM 的 ADC overhead", "整理 CIM 论文的系统映射方式"],
  },
  "devices-process": {
    title: "器件、工艺与先进节点",
    shortTitle: "器件 / 工艺",
    subtitle: "MOS 缩放、FinFET、GAA、短沟道效应、工艺集成、variability、可靠性和 device-circuit co-design。",
    description: "从器件物理进入先进工艺和电路影响的路线，帮助读懂 IEDM/VLSI Symposium 等论文。",
    outcomes: ["理解 MOS 缩放与短沟道效应", "读懂先进节点器件指标", "把器件变化映射到 SRAM、模拟、RF 和数字约束"],
    projectIdeas: ["做 MOSFET 缩放概念图", "整理 FinFET/GAA 指标表", "写一页 device-circuit co-design 笔记"],
  },
  "power-devices": {
    title: "功率器件与宽禁带半导体",
    shortTitle: "功率器件",
    subtitle: "SiC、GaN、MOSFET、IGBT、breakdown、Ron、热、封装、可靠性和电力电子应用。",
    description: "面向功率半导体和宽禁带器件的路线，连接器件指标、封装和系统应用。",
    outcomes: ["读懂功率器件指标", "理解 SiC/GaN 的优势与限制", "把器件、封装和系统可靠性连起来"],
    projectIdeas: ["整理 SiC/GaN 参数对照表", "做功率器件损耗计算表", "建立器件-封装-系统故障链路图"],
  },
  "advanced-packaging": {
    title: "先进封装与 Chiplet",
    shortTitle: "封装 / Chiplet",
    subtitle: "2.5D/3D、interposer、HBM、die-to-die、UCIe、热、测试、良率和系统 partition。",
    description: "理解 chiplet、先进封装、互连、良率、热和系统级架构取舍的路线。",
    outcomes: ["读懂先进封装剖面和互连指标", "理解 die-to-die 链路和 HBM 集成", "把封装选择连接到成本、良率和系统策略"],
    projectIdeas: ["做一份 chiplet 术语表", "比较 die-to-die 标准", "梳理 AI 加速器封装选择"],
  },
  "manufacturing-equipment-materials": {
    title: "制造、设备与材料",
    shortTitle: "制造 / 设备",
    subtitle: "光刻、刻蚀、沉积、CMP、量测、良率、设备、材料和供应链瓶颈。",
    description: "把工艺技术连接到设备公司、材料供应商和产业现实的路线。",
    outcomes: ["读懂设备/材料语境", "理解关键瓶颈设备", "把公司情报连接到工艺步骤"],
    projectIdeas: ["做设备-工艺矩阵", "按工艺模块梳理材料供应商", "写一个良率学习解释器"],
  },
  "eda-tools": {
    title: "EDA 与设计自动化",
    shortTitle: "EDA",
    subtitle: "综合、布局、布线、时序、验证、模拟自动化、ML/LLM for EDA 与设计效率。",
    description: "面向想构建设计工具而不只是使用工具的读者。",
    outcomes: ["阅读 DAC/ICCAD 论文", "实现小型 EDA 工具", "把算法连接到真实 netlist 与版图"],
    projectIdeas: ["做一个标题到主题的分类器", "实现一个小型 global placer", "做时序报告 dashboard"],
  },
  "analog-layout-verification": {
    title: "模拟版图与验证",
    shortTitle: "模拟版图",
    subtitle: "匹配、common-centroid、寄生、PEX debug、可靠性、EM/IR、LVS/DRC 和 signoff 习惯。",
    description: "把模拟原理图变成可制造硅片的实践路线，关注匹配版图、寄生提取、DRC/LVS、EM/IR、可靠性和评审习惯。",
    outcomes: ["完成匹配敏感模拟模块版图", "调试 post-layout 性能偏移", "建立 signoff checklist"],
    projectIdeas: ["做模拟版图 checklist", "写一个 PEX debug 案例", "建立匹配版图 pattern library"],
  },
  "hardware-security": {
    title: "硬件安全与可信芯片",
    shortTitle: "硬件安全",
    subtitle: "侧信道、PUF、木马检测、secure boot、TEE、密码加速器、故障注入和供应链可信。",
    description: "把安全威胁连接到电路、体系结构、验证和制造的路线。",
    outcomes: ["理解侧信道攻击", "阅读 PUF/Trojan/TEE 论文", "把安全机制映射到电路和系统层"],
    projectIdeas: ["做侧信道术语表", "建立 PUF/Trojan 论文地图", "跑一个小型 CPA 实验"],
  },
  "automotive-reliability-safety": {
    title: "汽车芯片、可靠性与功能安全",
    shortTitle: "汽车 IC",
    subtitle: "AEC-Q100、ISO 26262、ASIL、EMC/ESD、寿命、故障注入、diagnostic coverage 和产品认证。",
    description: "把芯片设计知识转化为汽车和高可靠产品思维的路线。",
    outcomes: ["读懂 qualification 表", "理解 ASIL 与 diagnostic coverage", "把芯片特性连接到 safety goal"],
    projectIdeas: ["做汽车 IC 品类地图", "写 ASIL 术语表", "把公司产品映射到汽车功能"],
  },
  "silicon-photonics": {
    title: "硅光与光互连",
    shortTitle: "硅光",
    subtitle: "光调制器、探测器、激光耦合、TIA/driver、WDM、共封装光学和光计算。",
    description: "连接光学、模拟/RF 电路、封装和数据中心互连系统的路线。",
    outcomes: ["读懂 optical link budget", "理解光电前端", "评估 CPO 和硅光 claims"],
    projectIdeas: ["做 optical-link budget worksheet", "比较 CPO 架构", "做硅光术语卡"],
  },
  "quantum-neuromorphic": {
    title: "量子控制与类脑芯片",
    shortTitle: "量子 / 类脑",
    subtitle: "低温 CMOS、qubit 控制/读出、SNN、事件驱动计算、memristor 和新兴计算接口。",
    description: "偏前沿的路线，适合在至少具备一个扎实电路或体系结构基础后进入。",
    outcomes: ["区分 quantum control chip 和 quantum device", "读懂 SNN/neuromorphic 指标", "识别仍处于研究探索阶段的内容"],
    projectIdeas: ["做 cryo-CMOS reading list", "仿真一个小型 SNN", "建立前沿 claim checklist"],
  },
};

const textMap: Record<string, string> = {
  "Learning content is a curated engineering guide. Use it to plan study, paper reading, and project work; verify equations, specs, and design advice with textbooks, datasheets, papers, and mentors before tape-out or publication.": CAVEAT_CN,
  "Before starting": "开始前",
  "These are the minimum ideas that make the route readable.": "这些是读懂本路线前最需要补齐的最小基础。",
  "Build while reading": "边读边补",
  "Add these gradually through papers, tools, and small projects.": "通过论文、工具和小项目逐步补齐这些能力。",
  "SiliconScope local search": "SiliconScope 本地检索",
  "Core analog CMOS reference.": "经典模拟 CMOS 参考书。",
  "Excellent bridge from metrics to real data-converter papers.": "从指标过渡到真实数据转换器论文的很好入口。",
  "Start with ISSCC/JSSC/CICC PMIC papers.": "从 ISSCC/JSSC/CICC 的 PMIC 论文开始。",
  "Use recent papers to see calibration patterns.": "用近期论文观察不同校准模式。",
  "Search clocking papers across venues.": "跨会议检索时钟相关论文。",
  "Classic RFIC path.": "经典 RFIC 学习路径。",
  "Search RF work across ISSCC/JSSC/RFIC.": "在 ISSCC/JSSC/RFIC 中检索 RF 相关工作。",
  "Measurement perspective.": "从测试测量角度补充理解。",
  "Start from metric-heavy papers.": "从指标密集的论文入手。",
  "Useful oscillator and PLL intuition.": "有助于建立振荡器和 PLL 直觉。",
  "Calculus and differential equations": "微积分与微分方程",
  "Linear algebra": "线性代数",
  "Probability and statistics": "概率统计",
  "Complex frequency-domain analysis": "复频域分析",
  "Signals and systems": "信号与系统",
  "Optimization basics": "优化基础",
  Electromagnetics: "电磁学",
  "Solid-state physics": "固体物理",
  "Semiconductor devices": "半导体器件",
  "Noise mechanisms": "噪声机制",
  "Process variation": "工艺波动",
  "Reliability basics": "可靠性基础",
  "Circuit analysis": "电路分析",
  "Analog electronics": "模拟电子学",
  "Digital logic": "数字逻辑",
  "Feedback and stability": "反馈与稳定性",
  "Sampling and quantization": "采样与量化",
  "Computer organization": "计算机组成",
  "Linux and Git": "Linux 与 Git",
  "Python or MATLAB": "Python 或 MATLAB",
  "SPICE simulation": "SPICE 仿真",
  "Verilog/SystemVerilog": "Verilog/SystemVerilog",
  "Cadence/Synopsys/Siemens EDA": "Cadence/Synopsys/Siemens EDA",
  "Paper reading and benchmark tables": "论文阅读与 benchmark 表格",
  "Device physics": "器件物理",
  "Basic MOS equations": "MOS 基本方程",
  "Small-signal circuits": "小信号电路",
  "Laplace/frequency response": "拉普拉斯与频率响应",
  "Noise basics": "噪声基础",
  "SPICE": "SPICE",
  "Op-amp/comparator basics": "运放/比较器基础",
  "ADC/DAC metrics": "ADC/DAC 指标",
  "PLL jitter": "PLL jitter",
  "PMIC loop behavior": "PMIC 环路行为",
  "Noise and mismatch": "噪声与失配",
  "PEX awareness": "寄生提取意识",
  "S-parameters": "S 参数",
  "Transmission lines": "传输线",
  Sampling: "采样",
  "PLL basics": "PLL 基础",
  "Linear equalization": "线性均衡",
  "Decision feedback": "判决反馈",
  "PAM4 metrics": "PAM4 指标",
  "Analog circuits": "模拟电路",
  "Smith chart": "Smith 圆图",
  "Noise figure": "噪声系数",
  Linearity: "线性度",
  "Spectrum analysis": "频谱分析",
};

const learningPhraseMap: Record<string, string> = {
  "Turn MOS equations into circuit intuition for gain, headroom, noise, and bandwidth.": "把 MOS 方程转化为对增益、余量、噪声和带宽的电路直觉。",
  "Explain gain-bandwidth trade-off": "解释增益-带宽取舍",
  "Read a simple op-amp schematic": "读懂一个简单运放原理图",
  "Identify mismatch-sensitive devices": "识别对失配敏感的器件",
  "Master the blocks that appear in ADC, PLL, PMIC, sensor, and RF papers.": "掌握 ADC、PLL、PMIC、传感器和 RF 论文里反复出现的基础模块。",
  "Create a block-level spec table": "建立模块级指标表",
  "Explain the dominant noise source": "解释主导噪声来源",
  "Run corners and Monte Carlo": "跑 corners 与 Monte Carlo",
  "Learn why clean schematics fail after layout, package, and measurement.": "理解为什么干净的原理图会在版图、封装和测试后失效。",
  "Write a test plan": "写一份测试计划",
  "Explain parasitic-induced poles": "解释寄生引入的极点",
  "Identify likely silicon debug probes": "识别可能需要的硅后 debug 探针",
  "Understand what ADC/DAC specs really measure.": "理解 ADC/DAC 指标到底在测什么。",
  "Explain why FoM can be misleading": "解释为什么 FoM 可能误导",
  "Read an FFT plot": "读懂 FFT 图",
  "Build a converter metric sheet": "建立转换器指标表",
  "See why architecture choice depends on bandwidth, resolution, power, and process.": "看清架构选择如何受带宽、分辨率、功耗和工艺共同约束。",
  "Classify a converter title correctly": "正确判断转换器论文标题所属架构",
  "Explain the main power bottleneck": "解释主要功耗瓶颈",
  "Identify calibration type": "识别校准类型",
  "Connect circuit nonidealities to digital correction and measurement setup.": "把电路非理想因素连接到数字校正和测试配置。",
  "Explain calibration convergence": "解释校准收敛",
  "List measurement equipment": "列出测试设备",
  "Avoid double-counting digital power": "避免重复计算数字功耗",
  "Identify every boundary where continuous-time behavior becomes sampled, quantized, timed, or digitally controlled.": "找出连续时间行为被采样、量化、定时或数字控制的所有边界。",
  "Draw an analog/digital boundary map": "画出模拟/数字边界图",
  "Explain metastability risk in a mixed-signal block": "解释混合信号模块中的亚稳态风险",
  "List registers needed for silicon debug": "列出硅后 debug 所需寄存器",
  "Understand how digital loops correct analog nonidealities without hiding bad measurements.": "理解数字环路如何校正模拟非理想，同时避免掩盖错误测量。",
  "Explain convergence vs tracking": "区分收敛与跟踪",
  "Avoid calibration benchmark traps": "避开校准 benchmark 陷阱",
  "Write a bring-up checklist": "写一份 bring-up checklist",
  "Plan simulation, emulation, validation, and lab debug for chips with analog cores and digital control.": "为带模拟核心和数字控制的芯片规划仿真、仿真加速、验证和实验室 debug。",
  "Create a mixed-signal verification plan": "建立混合信号验证计划",
  "Define model fidelity levels": "定义模型保真度层级",
  "Write first-silicon bring-up sequence": "写 first-silicon bring-up 顺序",
  "Make phase noise, jitter, spur, and lock time concrete.": "把相位噪声、jitter、spur 和 lock time 具体化。",
  "Read phase-noise plots": "读懂相位噪声图",
  "Explain jitter bandwidth": "解释 jitter 带宽",
  "List main spur sources": "列出主要 spur 来源",
  "Understand why CPPLL, ADPLL, fractional-N, MDLL, and injection locking exist.": "理解 CPPLL、ADPLL、fractional-N、MDLL 和注入锁定各自为什么存在。",
  "Classify PLL architecture from title": "从标题判断 PLL 架构",
  "Read lock-time specs": "读懂 lock-time 指标",
  "Connect clock generation to SerDes, ADC, RF, and digital timing closure.": "把时钟生成连接到 SerDes、ADC、RF 和数字时序收敛。",
  "Explain jitter allocation": "解释 jitter 分配",
  "Build a timing budget": "建立时序预算",
  "Identify system-level clock bottlenecks": "识别系统级时钟瓶颈",
  "Understand channel loss, ISI, eye opening, and link budget.": "理解信道损耗、ISI、眼图开口和链路预算。",
  "Explain insertion loss": "解释 insertion loss",
  "Read an eye diagram": "读懂眼图",
  "Build a simple channel model": "建立简化信道模型",
  "Understand transmitter, receiver, equalization, and CDR blocks.": "理解发射机、接收机、均衡和 CDR 模块。",
  "Map papers to TX/RX/CDR blocks": "把论文映射到 TX/RX/CDR 模块",
  "Explain adaptation loops": "解释自适应环路",
  "Read BER specs": "读懂 BER 指标",
  "Connect circuits to package, test, equalization training, and system constraints.": "把电路连接到封装、测试、均衡训练和系统约束。",
  "Explain de-embedding": "解释 de-embedding",
  "Build a link budget table": "建立链路预算表",
  "Learn matching, S-parameters, NF, IIP3, P1dB, and PAE.": "学习匹配、S 参数、NF、IIP3、P1dB 和 PAE。",
  "Use a Smith chart": "使用 Smith 圆图",
  "Explain NF vs gain": "解释 NF 与增益的关系",
  "Read PA efficiency plots": "读懂 PA 效率曲线",
  "Understand LNA, mixer, oscillator, PA, and synthesizer blocks.": "理解 LNA、mixer、oscillator、PA 和 synthesizer 模块。",
  "Classify RF paper blocks": "给 RF 论文模块分类",
  "Create RF chain budget": "建立 RF 链路预算",
  "Explain why layout is part of the circuit": "解释为什么版图也是电路的一部分",
  "Understand beamforming, phased arrays, packaging, and test.": "理解 beamforming、相控阵、封装和测试。",
  "Read EIRP and beam plots": "读懂 EIRP 与波束图",
  "List probe station requirements": "列出探针台测试需求",
  "Build the language of LDOs, buck/boost converters, and control loops.": "建立 LDO、buck/boost converter 和控制环路的语言。",
  "Explain efficiency curve shape": "解释效率曲线形状",
  "Read load transient plots": "读懂负载瞬态曲线",
  "Classify converter architecture": "判断 converter 架构",
  "Understand why modern PMIC papers mix inductors, capacitors, digital control, and package constraints.": "理解现代 PMIC 论文为什么会混合电感、电容、数字控制和封装约束。",
  "Explain conversion ratio": "解释转换比",
  "Identify inductor current ripple reduction": "识别电感电流纹波降低机制",
  "Map DPH papers to PMIC": "把 DPH 论文映射到 PMIC 方向",
  "Connect silicon PMICs to SoC rails, battery, package, EMI, and reliability.": "把硅片 PMIC 连接到 SoC 电源轨、电池、封装、EMI 和可靠性。",
  "Create a power tree": "建立 power tree",
  "Compare PMIC products": "比较 PMIC 产品",
  "Build a PMIC paper benchmark": "建立 PMIC 论文 benchmark",
  "Build AFE intuition for weak signals.": "建立弱信号 AFE 直觉。",
  "Read AFE noise tables": "读懂 AFE 噪声表",
  "Explain offset reduction": "解释 offset 降低方法",
  "Map signal bandwidth": "映射信号带宽",
  "Connect circuits to electrochemical, capacitive, optical, MEMS, and image sensors.": "把电路连接到电化学、电容、光学、MEMS 和图像传感器。",
  "Separate sensor and AFE specs": "区分传感器指标和 AFE 指标",
  "Explain column ADC use": "解释 column ADC 的用途",
  "Read a neural interface paper": "阅读一篇神经接口论文",
  "Handle wearable, implantable, test, calibration, and reliability constraints.": "处理可穿戴、植入式、测试、校准和可靠性约束。",
  "Write a measurement plan": "写一份测量计划",
  "Identify safety constraints": "识别安全约束",
  "Connect companies to sensor types": "把公司连接到传感器类型",
  "Write synthesizable RTL and test it.": "写出可综合 RTL 并完成测试。",
  "Avoid latch inference": "避免 latch inference",
  "Explain blocking vs nonblocking": "解释 blocking 与 nonblocking",
  "Create a small reusable module": "写一个小型可复用模块",
  "Move from modules to buses, integration, timing, and low power.": "从模块走向总线、集成、时序和低功耗。",
  "Read synthesis reports": "读懂综合报告",
  "Understand CDC risks": "理解 CDC 风险",
  "Explain power domains": "解释电源域",
  "Read accelerator and SoC papers with circuit-aware metrics.": "用电路感知的指标阅读加速器和 SoC 论文。",
  "Spot unfair benchmark claims": "识别不公平 benchmark claim",
  "Link architecture to memory hierarchy": "把架构连接到存储层次",
  "Build a comparison table": "建立对比表",
  "Understand setup, hold, slack, clocks, and constraints.": "理解 setup、hold、slack、clock 与 constraint。",
  "Explain slack": "解释 slack",
  "Identify false paths": "识别 false path",
  "Understand clock uncertainty": "理解 clock uncertainty",
  "Understand floorplan, placement, CTS, routing, and congestion.": "理解 floorplan、placement、CTS、routing 和 congestion。",
  "Explain congestion": "解释 congestion",
  "Read utilization": "读懂 utilization",
  "Understand clock skew": "理解 clock skew",
  "Handle extraction, IR/EM, DRC/LVS, and ECO closure.": "处理 extraction、IR/EM、DRC/LVS 和 ECO closure。",
  "Explain PEX impact": "解释 PEX 影响",
  "Understand ECO trade-offs": "理解 ECO 取舍",
  "Build testbench and assertion discipline.": "建立 testbench 与 assertion 习惯。",
  "Write verification plan": "写验证计划",
  "Explain coverage closure": "解释 coverage closure",
  "Debug a waveform": "调试波形",
  "Use formal methods and CDC/RDC analysis for deep bugs.": "用 formal 方法和 CDC/RDC 分析抓深层 bug。",
  "Explain proof bounds": "解释 proof bound",
  "Identify CDC crossings": "识别 CDC crossing",
  "Use assertions in design review": "在设计评审中使用 assertion",
  "Understand scan, BIST, ATPG, and production test cost.": "理解 scan、BIST、ATPG 与量产测试成本。",
  "Create DFT checklist": "建立 DFT checklist",
  "Explain fault coverage": "解释 fault coverage",
  "Understand test time vs cost": "理解测试时间与成本的关系",
  "Understand why data movement dominates accelerator design.": "理解为什么数据搬运主导加速器设计。",
  "Explain roofline": "解释 roofline",
  "Estimate memory bandwidth": "估算内存带宽",
  "Classify dataflows": "分类 dataflow",
  "Understand quantization, sparsity, compression, and accuracy trade-offs.": "理解量化、稀疏、压缩与精度取舍。",
  "Avoid misleading TOPS claims": "避免被 TOPS claim 误导",
  "Normalize benchmarks": "归一化 benchmark 口径",
  "Connect algorithm and hardware assumptions": "连接算法与硬件假设",
  "Connect chip architecture to package, software stack, and company strategy.": "把芯片架构连接到封装、软件栈和公司策略。",
  "Create architecture-company map": "建立架构-公司地图",
  "Compare datacenter vs edge": "比较数据中心与边缘场景",
  "Read product brief critically": "批判性阅读产品 brief",
  "Understand what LUTs, FFs, BRAMs, DSPs, and routing resources mean.": "理解 LUT、FF、BRAM、DSP 和 routing resource 的含义。",
  "Explain utilization": "解释 utilization",
  "Read timing slack": "读懂 timing slack",
  "Debug with ILA": "用 ILA debug",
  "Use FPGA for streaming, DSP, and prototype workloads.": "用 FPGA 做 streaming、DSP 和原型验证负载。",
  "Explain initiation interval": "解释 initiation interval",
  "Avoid timing bottlenecks": "避开时序瓶颈",
  "Compare HLS and RTL": "比较 HLS 与 RTL",
  "Know what transfers to ASIC and what does not.": "判断哪些经验能迁移到 ASIC，哪些不能。",
  "Identify FPGA-specific shortcuts": "识别 FPGA 特有捷径",
  "Plan verification reuse": "规划验证复用",
  "Know when to switch to ASIC flow": "知道何时切换到 ASIC flow",
  "Understand bitcells, read/write, sensing, stability, and assist circuits.": "理解 bitcell、读写、感测、稳定性和 assist 电路。",
  "Explain read/write margins": "解释读写裕量",
  "Compare SRAM/DRAM/Flash": "比较 SRAM/DRAM/Flash",
  "Read memory macro specs": "读懂 memory macro 指标",
  "Understand analog MAC, digital bit-serial compute, ADC overhead, and calibration.": "理解 analog MAC、digital bit-serial compute、ADC overhead 和校准。",
  "Compare analog and digital CIM": "比较模拟与数字 CIM",
  "Read TOPS/W carefully": "谨慎阅读 TOPS/W",
  "Identify accuracy loss mechanisms": "识别精度损失机制",
  "Connect macro claims to real neural-network workloads and memory traffic.": "把 macro claim 连接到真实神经网络负载和存储流量。",
  "Normalize benchmark assumptions": "归一化 benchmark 假设",
  "Identify missing overhead": "识别被遗漏的 overhead",
  "Build a CIM scorecard": "建立 CIM scorecard",
  "Understand MOSFET behavior and scaling effects.": "理解 MOSFET 行为和缩放效应。",
  "Read device plots": "读懂器件曲线",
  "Explain leakage paths": "解释 leakage path",
  "Understand variability sources": "理解 variability 来源",
  "Understand how lithography, etch, deposition, CMP, and metrology become a process flow.": "理解光刻、刻蚀、沉积、CMP 和量测如何组合成工艺流程。",
  "Explain process window": "解释 process window",
  "Identify integration bottlenecks": "识别集成瓶颈",
  "Read IEDM abstracts": "阅读 IEDM 摘要",
  "Connect device changes to SRAM, analog, RF, and digital constraints.": "把器件变化连接到 SRAM、模拟、RF 和数字约束。",
  "Explain PPA impact": "解释 PPA 影响",
  "Read node comparison tables": "阅读节点对比表",
  "Understand reliability trade-offs": "理解可靠性取舍",
  "Understand Rds(on), breakdown, capacitance, switching loss, and safe operating area.": "理解 Rds(on)、breakdown、电容、开关损耗和安全工作区。",
  "Read a power device datasheet": "读一份功率器件数据手册",
  "Explain FOM": "解释 FOM",
  "Estimate thermal limits": "估算热限制",
  "Understand why wide-bandgap devices are useful and difficult.": "理解宽禁带器件为什么有用也为什么难做。",
  "Explain WBG benefits": "解释 WBG 优势",
  "List reliability risks": "列出可靠性风险",
  "Connect gate driver to device": "把 gate driver 连接到器件特性",
  "Connect device, package, thermal, EMI, and converter design.": "连接器件、封装、热、EMI 和 converter 设计。",
  "Build device selection matrix": "建立器件选择矩阵",
  "Explain EMI paths": "解释 EMI 路径",
  "Compare discrete vs module": "比较分立器件与模块",
  "Understand wire bond, flip-chip, fan-out, interposer, and 3D stacking.": "理解 wire bond、flip-chip、fan-out、interposer 与 3D stacking。",
  "Explain package trade-offs": "解释封装取舍",
  "Read cross-section diagrams": "读懂剖面图",
  "Identify thermal bottlenecks": "识别热瓶颈",
  "Understand die-to-die links, HBM, interposer routing, and protocol choices.": "理解 die-to-die 链路、HBM、interposer routing 和协议选择。",
  "Read pJ/bit specs": "读懂 pJ/bit 指标",
  "Explain bandwidth density": "解释带宽密度",
  "Map memory placement": "映射存储放置方式",
  "Understand cost, yield, thermal, test, and partition decisions.": "理解成本、良率、热、测试和 partition 决策。",
  "Build partition scorecard": "建立 partition scorecard",
  "Explain known-good-die": "解释 known-good-die",
  "Connect packaging to company strategy": "把封装连接到公司策略",
  "Understand what lithography, etch, deposition, implant, CMP, and metrology do.": "理解光刻、刻蚀、沉积、离子注入、CMP 和量测各自做什么。",
  "Draw process flow": "画工艺流程",
  "Explain critical dimension": "解释 critical dimension",
  "Identify tool categories": "识别设备类别",
  "Understand process window, defect density, SPC, and yield learning.": "理解 process window、defect density、SPC 和 yield learning。",
  "Explain yield ramp": "解释 yield ramp",
  "Separate equipment and integration issues": "区分设备问题与集成问题",
  "Read process-control charts": "读懂过程控制图",
  "Map process steps to companies and bottleneck capabilities.": "把工艺步骤映射到公司和瓶颈能力。",
  "Build equipment matrix": "建立设备矩阵",
  "List materials categories": "列出材料类别",
  "Connect learning route to company module": "把学习路线连接到公司模块",
  "Build the graph and optimization toolbox behind EDA.": "建立 EDA 背后的图与优化工具箱。",
  "Recognize NP-hard formulations": "识别 NP-hard 问题形式",
  "Read benchmark tables": "阅读 benchmark 表",
  "Know common heuristics": "了解常见启发式算法",
  "Understand synthesis, placement, routing, timing, and verification as tool problems.": "把综合、布局、布线、时序和验证理解为工具问题。",
  "Explain placement objective": "解释 placement 目标",
  "Read timing graph": "读懂 timing graph",
  "Understand routing congestion": "理解 routing congestion",
  "Evaluate where ML/LLM helps and where it produces risky claims.": "评估 ML/LLM 在哪里有帮助、哪里容易产生高风险 claim。",
  "Define tool eval": "定义工具评测",
  "Avoid benchmark leakage": "避免 benchmark 泄漏",
  "Connect generated output to verification": "把生成结果连接到验证",
  "Translate mismatch theory into layout decisions.": "把失配理论转化为版图决策。",
  "Explain dummies": "解释 dummy 的作用",
  "Choose layout unit cells": "选择版图 unit cell",
  "Read matching specs": "读懂匹配指标",
  "Understand why post-layout simulation changes performance.": "理解 post-layout 仿真为什么会改变性能。",
  "Explain parasitic-induced pole": "解释寄生引入的极点",
  "Debug layout mismatch": "调试版图失配",
  "Create extraction checklist": "建立提取 checklist",
  "Build habits around DRC, LVS, EM/IR, reliability, and tape-out readiness.": "围绕 DRC、LVS、EM/IR、可靠性和 tape-out readiness 建立习惯。",
  "Create signoff checklist": "建立 signoff checklist",
  "Know when to waive": "知道何时可以 waive",
  "Write layout review notes": "写版图 review 记录",
  "Know what attackers can observe, control, and extract.": "知道攻击者可以观察、控制和提取什么。",
  "Explain attacker capability": "解释攻击者能力",
  "Define security goal": "定义安全目标",
  "Map leakage paths": "映射泄漏路径",
  "Connect measurements to implementation leakage.": "把测量结果连接到实现泄漏。",
  "Run a toy CPA": "跑一个 toy CPA",
  "Explain masking costs": "解释 masking 成本",
  "Read CHES abstract": "阅读 CHES 摘要",
  "Understand PUF, Trojan detection, TEE, and trusted design flows.": "理解 PUF、Trojan 检测、TEE 和可信设计流程。",
  "Create trust checklist": "建立可信 checklist",
  "Explain false positives": "解释 false positive",
  "Map security to product risk": "把安全问题映射到产品风险",
  "Understand AEC-Q100, HTOL, ESD, latch-up, lifetime, and FIT.": "理解 AEC-Q100、HTOL、ESD、latch-up、寿命和 FIT。",
  "Read a qualification matrix": "阅读 qualification matrix",
  "Explain FIT/lifetime": "解释 FIT/寿命",
  "Understand ISO 26262, ASIL, fault models, diagnostic coverage, redundancy, and lockstep.": "理解 ISO 26262、ASIL、fault model、diagnostic coverage、冗余和 lockstep。",
  "Read safety manual fragments": "阅读 safety manual 片段",
  "Explain diagnostic coverage": "解释 diagnostic coverage",
  "Map mechanisms to failure modes": "把机制映射到失效模式",
  "Apply reliability and safety to BMS, radar, PMIC, MCU, sensors, and domain controllers.": "把可靠性与功能安全应用到 BMS、radar、PMIC、MCU、sensor 和 domain controller。",
  "Build automotive IC taxonomy": "建立汽车 IC 分类表",
  "Connect companies to product categories": "把公司连接到产品品类",
  "Identify safety-critical blocks": "识别安全关键模块",
  "Understand waveguides, rings, modulators, photodiodes, insertion loss, and coupling.": "理解 waveguide、ring、modulator、photodiode、insertion loss 和 coupling。",
  "Read insertion loss specs": "读懂 insertion loss 指标",
  "Explain thermal tuning": "解释 thermal tuning",
  "Draw optical receiver chain": "画光接收链路",
  "Connect photonics to TIA, driver, CDR, SerDes, and system budgets.": "把光子器件连接到 TIA、driver、CDR、SerDes 和系统预算。",
  "Explain optical/electrical bandwidth": "解释光/电带宽",
  "Compare pJ/bit": "比较 pJ/bit",
  "List package constraints": "列出封装约束",
  "Understand co-packaged optics, WDM, laser integration, and thermal tuning.": "理解共封装光学、WDM、激光集成和 thermal tuning。",
  "Build CPO trade-off table": "建立 CPO 取舍表",
  "Explain reliability concerns": "解释可靠性顾虑",
  "Connect optics to chiplet packaging": "把光学连接到 chiplet 封装",
  "Pick quantum control, cryo-CMOS, SNN architecture, or emerging devices before reading too broadly.": "在广泛阅读前，先选择 quantum control、cryo-CMOS、SNN architecture 或 emerging device 作为主线。",
  "Write a reading boundary": "写清阅读边界",
  "Identify missing prerequisites": "识别缺失的先修知识",
  "Create paper buckets": "建立论文分桶",
  "Understand low-temperature noise, pulse generation, readout, event-driven timing, and scalability.": "理解低温噪声、脉冲生成、读出、事件驱动时序和可扩展性。",
  "Explain thermal budget": "解释 thermal budget",
  "Read readout specs": "读懂 readout 指标",
  "Compare coding schemes": "比较编码方式",
  "Turn frontier reading into a small simulation, benchmark, or taxonomy rather than hype.": "把前沿阅读变成小仿真、benchmark 或分类表，而不是停留在 hype。",
  "Define success metric": "定义成功指标",
  "Avoid vague claims": "避免模糊 claim",
  "Document assumptions": "记录假设",
};

const stageTitleMap: Record<string, string> = {
  "transistor intuition": "晶体管直觉",
  "reusable analog blocks": "可复用模拟模块",
  "layout and silicon reality": "版图与硅片现实",
  "converter language": "数据转换器语言",
  architectures: "架构选择",
  "calibration and test": "校准与测试",
  "analog-digital boundaries": "模拟/数字边界",
  "calibration and adaptation": "校准与自适应",
  "verification and bring-up": "验证与 bring-up",
  "phase-noise language": "相位噪声语言",
  "architecture choices": "架构选择",
  "system timing": "系统时序",
  "channel and eye": "信道与眼图",
  "PHY circuits": "PHY 电路",
  "measurement and system": "测试与系统",
  "RF language": "RF 语言",
  "RF blocks": "RF 模块",
  "mmWave arrays and measurement": "毫米波阵列与测试",
  "regulators and loops": "稳压器与环路",
  "hybrid and integrated converters": "混合与集成转换器",
  "system power": "系统供电",
  "low-noise front ends": "低噪声前端",
  "sensor systems": "传感系统",
  "product constraints": "产品约束",
  "RTL discipline": "RTL 纪律",
  "SoC flow": "SoC 流程",
  "architecture papers": "体系结构论文",
  "timing reports": "时序报告",
  "place and route": "布局布线",
  "signoff thinking": "signoff 思维",
  "simulation and assertions": "仿真与断言",
  "formal and CDC": "formal 与 CDC",
  "DFT and silicon test": "DFT 与硅后测试",
  "dataflow and memory": "数据流与存储",
  "precision and sparsity": "精度与稀疏性",
  "product architecture": "产品架构",
  "fabric and RTL": "FPGA fabric 与 RTL",
  acceleration: "加速",
  "FPGA to ASIC thinking": "从 FPGA 到 ASIC 的思维转换",
  "memory circuits": "存储电路",
  "CIM circuits": "CIM 电路",
  "system mapping": "系统映射",
  "device physics": "器件物理",
  "process integration": "工艺集成",
  "device-circuit co-design": "器件-电路协同设计",
  "power device language": "功率器件语言",
  "SiC and GaN": "SiC 与 GaN",
  "device-package-system": "器件-封装-系统",
  "package map": "封装地图",
  "chiplet I/O": "Chiplet I/O",
  "system trade-offs": "系统级取舍",
  "process modules": "工艺模块",
  "yield and control": "良率与控制",
  "supply chain": "供应链",
  "algorithm base": "算法基础",
  "design-flow problems": "设计流程问题",
  "AI for EDA": "AI for EDA",
  "matching layout": "匹配版图",
  "PEX debug": "PEX 调试",
  signoff: "signoff",
  "threat models": "威胁模型",
  "side channels and countermeasures": "侧信道与防护",
  "trust and supply chain": "可信与供应链",
  "reliability language": "可靠性语言",
  "functional safety": "功能安全",
  "automotive applications": "汽车应用",
  "optical devices": "光器件",
  "optoelectronic links": "光电链路",
  "system and packaging": "系统与封装",
  "choose a spine": "选择主线",
  "interface circuits": "接口电路",
  "verifiable project": "可验证项目",
};

const lessonTitleMap: Record<string, string> = {
  "MOS small-signal model": "MOS 小信号模型",
  "Loop gain and phase margin": "环路增益与相位裕度",
  "Input-referred noise": "输入参考噪声",
  "Mixed-signal boundary map": "数模混合边界图",
  "Reading ADC FoM correctly": "正确阅读 ADC FoM",
  "SAR ADC binary search": "SAR ADC 二分搜索",
  "Delta-sigma noise shaping": "Delta-sigma 噪声整形",
  "Phase noise to integrated jitter": "从相位噪声到积分 jitter",
  "ADPLL DTC resolution and spur": "ADPLL、DTC 分辨率与 spur",
  "SerDes eye diagram and equalization": "SerDes 眼图与均衡",
  "PAM4 receiver CDR intuition": "PAM4 接收机 CDR 直觉",
  "RF noise figure": "RF 噪声系数",
  "mmWave phased array": "毫米波相控阵",
  "LDO loop stability": "LDO 环路稳定性",
  "Hybrid DC-DC converter classification": "Hybrid DC-DC converter 分类",
  "Sensor AFE noise": "Sensor AFE 噪声",
  "CMOS image sensor column ADC": "CMOS 图像传感器 column ADC",
  "RTL and FSM discipline": "RTL 与 FSM 纪律",
  "SoC clock-domain crossing": "SoC 时钟域跨越",
  "Setup/hold timing report reading": "setup/hold 时序报告阅读",
  "Clock-tree skew and latency": "时钟树 skew 与 latency",
  "Assertions and coverage": "断言与覆盖率",
  "Scan, ATPG, and BIST": "Scan、ATPG 与 BIST",
  "Systolic array dataflow": "Systolic array 数据流",
  "TOPS/W benchmark traps": "TOPS/W benchmark 陷阱",
  "FPGA utilization and timing": "FPGA 资源利用率与时序",
  "FPGA streaming accelerator": "FPGA 流式加速器",
  "6T SRAM read stability": "6T SRAM 读稳定性",
  "Analog CIM and ADC overhead": "模拟 CIM 与 ADC overhead",
  "MOSFET scaling and short-channel effects": "MOSFET 缩放与短沟道效应",
  "Process window and yield learning": "工艺窗口与良率学习",
  "SiC and GaN power devices": "SiC 与 GaN 功率器件",
  "Chiplet die-to-die links": "Chiplet die-to-die 链路",
  "Placement and routing as optimization": "把 placement/routing 当成优化问题",
  "Common-centroid layout intuition": "Common-centroid 版图直觉",
  "Side-channel CPA intuition": "侧信道 CPA 直觉",
  "AEC-Q100 qualification map": "AEC-Q100 认证地图",
  "Silicon photonics link budget": "硅光 link budget",
  "Cryogenic CMOS frontier map": "低温 CMOS 前沿地图",
};

function translateText(value: string | undefined | null) {
  if (!value) return value ?? "";
  const direct = textMap[value] || learningPhraseMap[value];
  if (direct) return direct;
  const stageMatch = value.match(/^Stage (\d+): (.+)$/);
  if (stageMatch) {
    const translated = stageTitleMap[stageMatch[2]] || stageMatch[2];
    return `阶段 ${stageMatch[1]}：${translated}`;
  }
  return value;
}

function translateArray(values: string[] | undefined) {
  return values?.map((value) => translateText(value));
}

function localizePrereqGroup(group: PrerequisitesGroup): PrerequisitesGroup {
  return {
    ...group,
    title: translateText(group.title),
    note: translateText(group.note),
    items: group.items.map((item) => translateText(item)),
  };
}

function localizeResource(resource: LearningResource): LearningResource {
  return {
    ...resource,
    provider: translateText(resource.provider),
    note: translateText(resource.note),
  };
}

function localizeModule(module: RoadmapModule): RoadmapModule {
  return {
    ...module,
    title: translateText(module.title),
    purpose: translateText(module.purpose),
    lessonPlaceholders: module.lessonPlaceholders.map((item) => translateText(item)),
  };
}

function localizeStage(stage: RoadmapStage): RoadmapStage {
  return {
    ...stage,
    title: translateText(stage.title),
    goal: translateText(stage.goal),
    checkpoints: translateArray(stage.checkpoints),
    resources: stage.resources?.map(localizeResource),
    modules: stage.modules.map(localizeModule),
  };
}

export function localizeRoadmapDisplay(roadmap: LearningRoadmapSeed): LearningRoadmapSeed {
  const route = routeText[roadmap.slug] || {};
  return {
    ...roadmap,
    ...route,
    targetUsers: roadmap.targetUsers.map((user) => targetUserLabels[user] || user),
    prerequisites: translateArray(roadmap.prerequisites) || [],
    foundation: translateArray(roadmap.foundation) || [],
    prerequisitesGroups: roadmap.prerequisitesGroups?.map(localizePrereqGroup),
    stages: roadmap.stages.map(localizeStage),
    caveat: translateText(roadmap.caveat) || CAVEAT_CN,
    outcomes: route.outcomes || translateArray(roadmap.outcomes),
    projectIdeas: route.projectIdeas || translateArray(roadmap.projectIdeas),
  };
}

export function localizeRoadmapsDisplay(roadmaps: LearningRoadmapSeed[]) {
  return roadmaps.map(localizeRoadmapDisplay);
}

export function localizeLessonDisplay(lesson: DailyLessonSeed): DailyLessonSeed {
  return {
    ...lesson,
    title: lessonTitleMap[lesson.title] || translateText(lesson.title),
    sectionPlaceholders: Object.fromEntries(
      Object.entries(lesson.sectionPlaceholders).map(([key, value]) => [key, LESSON_TEMPLATE_CN[key] || translateText(value)]),
    ),
  };
}

export function localizeLessonsDisplay(lessons: DailyLessonSeed[]) {
  return lessons.map(localizeLessonDisplay);
}

export function localizeRouteFamiliesDisplay(families: RouteFamilySeed[]): RouteFamilySeed[] {
  return families.map((family) => ({
    ...family,
    ...(routeFamilies[family.id] || {}),
  }));
}

export function localizeFoundationsDisplay(groups: FoundationGroupSeed[]): FoundationGroupSeed[] {
  return groups.map((group) => ({
    ...group,
    ...(foundationGroups[group.title] || {
      title: translateText(group.title),
      note: translateText(group.note),
      items: group.items.map((item) => translateText(item)),
    }),
  }));
}
